name: Build ASP.NET Core App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - run: dotnet restore ./icons/icons.csproj
      - run: dotnet build ./icons/icons.csproj --configuration Release
